# Generated by Django 4.0.2 on 2022-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=350)),
                ('post_author', models.CharField(max_length=50)),
                ('post_pub_date', models.DateField()),
                ('post_content', models.CharField(max_length=5000000)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('post_genre', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
