# Generated by Django 4.0.2 on 2022-05-24 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(default='', max_length=70, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
