# Generated by Django 4.0.2 on 2022-05-27 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.CharField(max_length=5000)),
                ('f_name', models.CharField(default='', max_length=99)),
                ('l_name', models.CharField(default='', max_length=99)),
                ('address', models.CharField(default='', max_length=1500)),
                ('email', models.CharField(default='', max_length=75, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(default='', max_length=70, validators=[django.core.validators.MaxLengthValidator(13)])),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.MaxLengthValidator(13)]),
        ),
    ]
