# Generated by Django 4.0.2 on 2022-05-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='email',
            field=models.CharField(default='', max_length=75, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
